server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # TRUCO PRO: Docker Service Discovery
  # Promtail le pregunta a Docker: "¿Qué contenedores hay vivos?"
  # y automáticamente empieza a leer sus logs.
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    
    relabel_configs:
      # Esto limpia los nombres para que en Grafana se vean bonitos
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      # Esto captura las etiquetas "labels" que pusimos en el docker-compose
      - source_labels: ['__meta_docker_container_label_service']
        target_label: 'service_type'
